### ISSUE TITLE
How to run with Spark2.1.1 and Nodejs

### ISSUE THREAD

**Issue by jungfrau70** [spark-server/spark-server#1]
Hello Tobi,
I found your work recently, and I was very interested in it.
Now, I was testing it with spark 2.3.1. and node 8.10.0, and I encountered the issues. 
Its container is made successfully, but the service is not working properly when I send the rest api request and it returns the error.
Would you please help me to fix it?

Attached is the Dockerfile that I modified.

Your helps would be highly appreciated.
Thanks and regards, InHwan.

**Comment by tobilg** [comment]
Can you please add more details @inhwane? Thanks!
